# Generated by Django 3.2 on 2021-06-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imag_clie',
            field=models.ImageField(blank=True, height_field='400', null=True, upload_to='images/faces/', width_field='400'),
        ),
    ]
