# Generated by Django 3.2 on 2021-06-04 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_imag_clie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imag_clie',
            field=models.ImageField(blank=True, null=True, upload_to='dmca/static/images/faces/'),
        ),
    ]
