# Generated by Django 3.2 on 2021-06-29 01:24

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_user_imag_clie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imag_clie',
            field=models.ImageField(blank=True, default='dmca/static/images/faces/default-profile-picture.jpg', null=True, upload_to='dmca/static/images/faces/', validators=[accounts.models.validate_image]),
        ),
    ]
