# Generated by Django 3.2 on 2021-05-21 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id_clie', models.AutoField(primary_key=True, serialize=False)),
                ('imag_clie', models.ImageField(blank=True, height_field='400', null=True, upload_to='images/faces/', width_field='400')),
            ],
            options={
                'verbose_name_plural': 'clients',
            },
        ),
        migrations.CreateModel(
            name='nicks',
            fields=[
                ('id_nick', models.AutoField(primary_key=True, serialize=False)),
                ('nick', models.CharField(max_length=45)),
                ('prio', models.CharField(max_length=45)),
                ('clients_id_clie', models.ForeignKey(db_column='clients_id_clie', on_delete=django.db.models.deletion.CASCADE, to='dmca.clients')),
            ],
            options={
                'verbose_name_plural': 'nicks',
            },
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id_page', models.AutoField(primary_key=True, serialize=False)),
                ('name_page', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'pages',
            },
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('plan', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Plans',
            },
        ),
        migrations.CreateModel(
            name='TubePages',
            fields=[
                ('id_tube_pages', models.AutoField(primary_key=True, serialize=False)),
                ('name_tube_page', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'tube_pages',
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id_work', models.AutoField(primary_key=True, serialize=False)),
                ('name_work', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'workers',
            },
        ),
        migrations.CreateModel(
            name='TubeReports',
            fields=[
                ('id_tube_repo', models.AutoField(primary_key=True, serialize=False)),
                ('stat_tube', models.CharField(max_length=45)),
                ('date_tube', models.DateField()),
                ('clients_id_clie', models.ForeignKey(db_column='clients_id_clie', on_delete=django.db.models.deletion.CASCADE, to='dmca.clients')),
            ],
            options={
                'verbose_name_plural': 'tube_reports',
            },
        ),
        migrations.CreateModel(
            name='TubeHasPages',
            fields=[
                ('id_tube_pages', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('tube_urls', models.CharField(max_length=45)),
                ('tube_pages_id_tube_pages', models.ForeignKey(db_column='tube_pages_id_tube_pages', on_delete=django.db.models.deletion.CASCADE, to='dmca.tubepages')),
                ('tube_reports_id_tube_repo', models.ForeignKey(db_column='tube_reports_id_tube_repo', on_delete=django.db.models.deletion.CASCADE, to='dmca.tubereports')),
            ],
            options={
                'verbose_name_plural': 'tube_has_pages',
            },
        ),
        migrations.CreateModel(
            name='NicksHasPages',
            fields=[
                ('id_nick_page', models.AutoField(primary_key=True, serialize=False)),
                ('nicks_id_nick', models.ForeignKey(db_column='nicks_id_nick', on_delete=django.db.models.deletion.CASCADE, to='dmca.nicks')),
                ('pages_id_pages', models.ForeignKey(db_column='pages_id_pages', on_delete=django.db.models.deletion.CASCADE, to='dmca.pages')),
            ],
            options={
                'verbose_name_plural': 'nicks_has_pages',
            },
        ),
        migrations.CreateModel(
            name='GoogleReports',
            fields=[
                ('id_goog_repo', models.AutoField(primary_key=True, serialize=False)),
                ('date_gore', models.DateField()),
                ('id_clai_gore', models.CharField(max_length=45)),
                ('type_clai_gore', models.CharField(max_length=45)),
                ('stat_gore', models.CharField(max_length=45)),
                ('urls_gore', models.TextField()),
                ('cant_urls_gore', models.IntegerField()),
                ('clients_id_clie', models.ForeignKey(db_column='clients_id_clie', on_delete=django.db.models.deletion.CASCADE, to='dmca.clients')),
            ],
            options={
                'verbose_name_plural': 'google_reports',
            },
        ),
        migrations.AddField(
            model_name='clients',
            name='plan_id',
            field=models.ForeignKey(blank=True, db_column='plans_id_plan', null=True, on_delete=django.db.models.deletion.CASCADE, to='dmca.plans'),
        ),
        migrations.AddField(
            model_name='clients',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clients',
            name='worker_id_work',
            field=models.ForeignKey(blank=True, db_column='worker_id_work', null=True, on_delete=django.db.models.deletion.CASCADE, to='dmca.workers'),
        ),
    ]
