# Generated by Django 3.2 on 2021-06-03 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='imag_clie',
        ),
    ]
