# Generated by Django 3.2 on 2021-05-18 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmca', '0002_authuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthUser',
        ),
    ]
