# Generated by Django 3.2 on 2021-05-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmca', '0003_delete_authuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='is_client',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
