# Generated by Django 3.2 on 2021-06-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmca', '0003_auto_20210608_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='id_plan',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
