# Generated by Django 3.2 on 2021-06-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmca', '0004_alter_plans_id_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='id_plan',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plans',
            name='plan',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
