# Generated by Django 3.2 on 2021-05-18 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmca', '0005_auto_20210518_1844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
