# Generated by Django 3.2 on 2021-07-06 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmca', '0006_auto_20210629_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='tubepages',
            name='contact_tube',
            field=models.CharField(default=None, max_length=120),
            preserve_default=False,
        ),
    ]
