# Generated by Django 3.2 on 2021-08-03 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmca', '0008_clients_data_assign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='data_assign',
            field=models.DateField(default=datetime.datetime(2021, 9, 3, 11, 0, 2, 740057)),
        ),
    ]
