# Generated by Django 3.2 on 2021-08-03 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmca', '0009_alter_clients_data_assign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='data_assign',
        ),
        migrations.AddField(
            model_name='clients',
            name='date_assign',
            field=models.DateField(default=datetime.datetime(2021, 9, 3, 13, 39, 38, 817674)),
        ),
    ]
