# Generated by Django 3.2 on 2021-08-13 22:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmca', '0011_alter_clients_date_assign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='date_assign',
            field=models.DateField(default=datetime.datetime(2021, 9, 13, 18, 39, 11, 504473)),
        ),
        migrations.AlterField(
            model_name='nicks',
            name='prio',
            field=models.CharField(choices=[('Normal', 'Normal'), ('High', 'Alta')], default='normal', max_length=45, verbose_name='Priority'),
        ),
    ]
