# Generated by Django 3.2 on 2021-08-13 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmca', '0012_auto_20210813_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='date_assign',
            field=models.DateField(default=datetime.datetime(2021, 9, 13, 18, 42, 58, 730618)),
        ),
    ]
