# Generated by Django 3.2 on 2021-08-14 02:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmca', '0013_alter_clients_date_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='nicks',
            name='pages',
            field=models.ManyToManyField(to='dmca.Pages'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='date_assign',
            field=models.DateField(default=datetime.datetime(2021, 9, 13, 22, 12, 31, 615415)),
        ),
        migrations.DeleteModel(
            name='NicksHasPages',
        ),
    ]
