# Generated by Django 3.2 on 2021-08-14 03:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dmca', '0014_auto_20210813_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='date_assign',
            field=models.DateField(default=datetime.datetime(2021, 9, 13, 23, 43, 20, 340496)),
        ),
        migrations.CreateModel(
            name='NicksPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmca.nicks')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmca.pages')),
            ],
        ),
        migrations.AlterField(
            model_name='nicks',
            name='pages',
            field=models.ManyToManyField(through='dmca.NicksPages', to='dmca.Pages'),
        ),
    ]
