# Generated by Django 3.2 on 2021-09-06 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmca', '0015_auto_20210813_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='date_assign',
            field=models.DateField(default=datetime.datetime(2021, 10, 7, 19, 38, 56, 612490)),
        ),
    ]
