# Generated by Django 3.2 on 2021-09-21 23:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmca', '0029_alter_clients_date_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='nicks',
            name='slug',
            field=models.SlugField(default='nick', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clients',
            name='date_assign',
            field=models.DateField(default=datetime.datetime(2021, 10, 22, 19, 29, 56, 232022)),
        ),
        migrations.AlterField(
            model_name='nicks',
            name='prio',
            field=models.CharField(choices=[('Normal', 'Normal'), ('High', 'High')], default='normal', max_length=45, verbose_name='Priority'),
        ),
    ]
