# Generated by Django 3.2 on 2021-09-22 00:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmca', '0032_alter_clients_date_assign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nicks',
            name='slug',
        ),
        migrations.AlterField(
            model_name='clients',
            name='date_assign',
            field=models.DateField(default=datetime.datetime(2021, 10, 22, 20, 49, 11, 559968)),
        ),
    ]
