# Generated by Django 3.2 on 2021-09-28 03:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmca', '0033_auto_20210921_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlereports',
            name='stat_gore',
        ),
        migrations.AlterField(
            model_name='clients',
            name='date_assign',
            field=models.DateField(default=datetime.datetime(2021, 10, 28, 23, 33, 46, 154817)),
        ),
        migrations.AlterField(
            model_name='googlereports',
            name='type_clai_gore',
            field=models.CharField(choices=[('DMCA-IMAGES', 'DMCA-IMAGES'), ('DMCA-CONTENT', 'DMCA-CONTENT')], default='DMCA-IMAGES', max_length=45, verbose_name='Type of claim'),
        ),
    ]
