# Generated by Django 3.2 on 2021-09-30 21:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dmca', '0035_auto_20210930_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='date_assign',
            field=models.DateField(default=datetime.datetime(2021, 10, 31, 17, 34, 55, 20766)),
        ),
        migrations.AlterField(
            model_name='tubereports',
            name='clients_id_clie',
            field=models.ForeignKey(db_column='clients_id_clie', on_delete=django.db.models.deletion.CASCADE, to='dmca.clients'),
        ),
        migrations.AlterField(
            model_name='tubereports',
            name='id_tube_pages',
            field=models.ForeignKey(db_column='tubepages_id_tube_pages', on_delete=django.db.models.deletion.CASCADE, to='dmca.tubepages'),
        ),
    ]
