# Generated by Django 3.2 on 2021-09-30 21:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dmca', '0036_auto_20210930_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tubereports',
            name='id_tube_pages',
        ),
        migrations.AddField(
            model_name='tubereports',
            name='tubepages_id_tube_pages',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dmca.tubepages'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clients',
            name='date_assign',
            field=models.DateField(default=datetime.datetime(2021, 10, 31, 17, 40, 28, 981313)),
        ),
        migrations.AlterField(
            model_name='tubereports',
            name='clients_id_clie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmca.clients'),
        ),
    ]
