# Generated by Django 3.2 on 2021-09-30 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmca', '0037_auto_20210930_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tubereports',
            old_name='tubepages_id_tube_pages',
            new_name='id_tube_pages',
        ),
        migrations.AlterField(
            model_name='clients',
            name='date_assign',
            field=models.DateField(default=datetime.datetime(2021, 10, 31, 19, 10, 51, 804167)),
        ),
    ]
